version: "3.8"

services:
  api:
    build: dev/.
    working_dir: /api
    container_name: 'store_app'
    stdin_open: true
    tty: true
    command: python manage.py runserver 0.0.0.0:8000 # --settings=e_survey.settings_develop
    ports:
      - "8000:8000"
    volumes: # is no too necesary in prod. environment
      - .:/api
    environment:
      - DJANGO_DEBUG=True
  # this service will use same image, and once the migration is done it will be stopped
    # web_migrations:
    #   build: .
    #   command: ./manage.py migrate